type TimeSpan {
  from: String
  to: String
}

enum LessonFlag {
  SUBSTITUTE
  REPLACEMENT
  CANCELED
  NOTDONE
  EVENT
  OFFICEHOURS
  HALFTIME
  CLUB
  ONLINE
  EXAM
}

type Lesson {
  name: String!
  teacher: String
  className: String
  room: String
  flags: [LessonFlag]
}

type Day {
  lessons: [[Lesson]]
}

type WeeklyTimetable {
  className: String
  room:String
  week: Int!
  scheduleDefinitions: [TimeSpan]
  days: [Day]
}